### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Kroc** [FellippeHeitor/INI-Manager#2]
Hello there. Thank you for your code. I need to make use of it, but it would be better if there were some kind of specific license attached. A 2-clause BSD or MIT would be ideal. GPL would preclude me from being able to use the code in my projects.

Kind regards,
Kroc Camen.

**Comment by FellippeHeitor** [comment]
Hello,

Thanks for your interest in the library.

I have just placed it under the MIT license, hope it’s useful for your project.

Let me know if you find any issues or need any assistance using INI Manager.

Fellippe
