### ISSUE TITLE
Troubles with inline comments

### ISSUE THREAD

**Issue by Kroc** [FellippeHeitor/INI-Manager#4]
I've just noticed that I can't read a semi-colon separated file-list from a value, because the semi-colon is taken as a comment. Comments on the same line as values is not common behaviour because there would be no way to include a semi-colon in a text-message; translations, for example. More so the fact that it doesn't require white-space beforehand, i.e. "value;comment" (BAD) vs. "value ;comment" (OK) which would allow semi-colon separated lists to be supported, e.g. "value;value;value ;comment".

There's a couple of things you could do here:
* An option to disable in-line comments (that is, include them in the value)
* Require white-space before a comment marker

**Comment by FellippeHeitor** [comment]
Are those inside quotation marks?

**Comment by Kroc** [comment]
Nope. Example file:

```ini
[global]
name=GZDoom
rank=100

[engines]
1=gzdoom
2=gzdoom-34

[engine.gzdoom]
title=GZDoom v3.4.1 (64-Bit)
exe=gzdoom.exe
ver=341
bit=64
vid=32
kin=G
cfg=gzdoom
save=gzdoom
tags=vanilla,deh,no-limit,mbf,acs,decorate,udmf,zscript
iwads=*.WAD;*.PK3;*.PK7;*.IWAD;*.IPK3
pwads=*.WAD;*.PK3;*.PK7
auto=brightmaps.pk3;lights.pk3

[engine.gzdoom-34]
title=GZDoom v3.4.1 (64-Bit)
exe=gzdoom.exe
ver=341
bit=64
vid=32
kin=G
cfg=gzdoom-34
save=gzdoom
tags=vanilla,deh,no-limit,mbf,acs,decorate,udmf,zscript
iwads=*.WAD;*.PK3;*.PK7;*.IWAD;*.IPK3
pwads=*.WAD;*.PK3;*.PK7
auto=brightmaps.pk3;lights.pk3
```

Edit: Does that mean I should, and that would solve it?

**Comment by Kroc** [comment]
Adding the speech marks fixed it -- my bad; I wasn't aware of that!

**Comment by FellippeHeitor** [comment]
Glad to hear! Glad to know the library will be useful to you as well.

**Comment by Kroc** [comment]
Thank you, it's helped get things off the ground quickly!

**Comment by FellippeHeitor** [comment]
While reconsidering the behavior of ; for comments I noticed how GitHub colorized your sample ini file above, have a look at how it colored what comes after the semicolons. :-)
