### ISSUE TITLE
Any value (including strings) containing square brackets is not accessible

### ISSUE THREAD

**Issue by Kroc** [FellippeHeitor/INI-Manager#5]
```ini
[games.doom64-rtr]
iwad=DOOM2
pre="D64RTR_BRIGHTMAPS.PK3"
pwad="D64RTR[v1.5].WAD"
tags=gzdoom
```

I've found that any value that contains square brackets (including contained within strings!) doesn't read; my program gets back nothing (`""`) for the `pwad` property.

**Comment by FellippeHeitor** [comment]
Oops. I'll have a look. Thanks for reporting.
