### ISSUE TITLE
Working with multiple files may cause mix-ups

### ISSUE THREAD

**Issue by FellippeHeitor** [FellippeHeitor/INI-Manager#8]
After working with https://github.com/FellippeHeitor/ControleDeOficios, it has been found that INI-Manager may run into issues when multiple `.ini` files are dealt with in the same session, namely that files may get mixed up at commit time.

A solution may be to keep an array of file numbers - and start working with high numbered handles in order to avoid causing issues with the host application eventually using FREEFILE too, so that (i) the same file being written to will be using the same handle and (ii) the files can remain open throughout the session.

**Comment by Kroc** [comment]
If QB64 could pass UDTs in function arguments, then INI manager could take and return a UDT for any method, meaning the programmer can have more than one INI-UDT in use at a time.

**Comment by FellippeHeitor** [comment]
QB64 can pass UDTs in function arguments. I don't understand the proposal, though. How did you envision it?

**Comment by Kroc** [comment]
I haven't coded QB64 for a little while, so I'm rusty, but the idea is that the caller prepares an instance of a UDT that INI-Manager defines. This UDT defines the complete state that INI-Manager needs to read an INI file. Therefore, if the caller has multiple instances of this UDT, then calls to INI-Manager with different UDTs will pass-in separate INI files & state without conflict with one another. This is typical with Functional and Structure/Protocol-orientated programming.

**Comment by FellippeHeitor** [comment]
I see. Thanks!
